import Head from "next/head";
import Button from "../components/atoms/Button/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button text="shop" link="#" type="primary" />
      <Button text="ver más" link="#" type="secondary" />
    </div>
  );
}
